### ISSUE TITLE
Cors socket problems

### ISSUE THREAD

**Issue by hannaforssell** [viktormelin/gridpainter-grupp-2#51]
App is deployed at Digital Ocean (https://gridpainter-grupp-2-839p7.ondigitalocean.app/), but when changing socket connection (currently in files chat.ts and draw.ts in frontend) from localhost to deployed site cors problems appears.

**Comment by etrigo** [comment]
@hannaforssell har du testat lägga till:
```
origin: "*"
```
i cors config för socket i backend?

Eller är problemet bara frontendrelaterat?

**Comment by hannaforssell** [comment]
Japp, har testat med det fram och tillbaka utan framgång. Men du har nog rätt att den ska vara med.
