### ISSUE TITLE
create drawings route + endpoints

### ISSUE THREAD

**Issue by etrigo** [viktormelin/gridpainter-grupp-2#58]
A drawing is the result from a group of users free painting. We need one route for drawings eg. ...api/drawings

# Then we need endpoints on that route. 
### ...api/drawings/add
POST to save a new drawing with data according to suggestion in issue #38 

### ...api/drawings/get
GET to collect all drawings to display when clicking saved pictures page #40 

### Questions:
Should we use user_id or just save username?

**Comment by etrigo** [comment]
refering to issue #38 colloection drawings

**Comment by hannaforssell** [comment]
I am using user_id in this.
